name: Build and Publish NPM Package

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  publish_on_merge:
    permissions:
      contents: write
      packages: write
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/npm-reusable-steps.yml
    with:
      checkout-ref: ${{ github.event.pull_request.merge_commit_sha }}
      node-version: '20'
      registry-url: 'https://npm.pkg.github.com'
      scope: '@wilsonwong1990'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  publish_manual:
    permissions:
      contents: write
      packages: write
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/npm-reusable-steps.yml
    with:
      node-version: '20'
      registry-url: 'https://npm.pkg.github.com'
      scope: '@wilsonwong1990'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
